version: '3'

services:
  activemq:
    image: quay.io/artemiscloud/activemq-artemis-broker
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"

    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin